ifndef::imagesdir[:imagesdir: ../images]

[[section-runtime-view]]
== Runtime View


ifdef::arc42help[]
[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...


.Further Information

See https://docs.arc42.org/section-6/[Runtime View] in the arc42 documentation.

****
endif::arc42help[]

=== Sign up

The user wants to create a new account and register it for the future.
Data must be valid and not collide with some account that already exists.

[plantuml,"SignUp",png]
----

actor User
participant WebApp
participant UserService
database DataBase


User --> WebApp: Select to sign up

loop Until a new user is added or going back to LogIn
    WebApp --> User: Show sign up fields
    User --> WebApp: Fill sign up fields and press add user
    WebApp --> UserService: Validate sign up fields
    UserService --> DataBase: Check that user does not exist
    DataBase --> DataBase: Save the new user
    DataBase --> UserService: Response 
    UserService --> WebApp: Response
    WebApp --> User: Informs that the user is correctly added

    alt Validations are incorrect or user already exists
        WebApp --> User: Show errors and retry filling the fields
    end
end


----


=== Log in

The user wants to log in with an account that has already been created.

[plantuml,"LogIn",png]
----
actor User
participant WebApp
participant AuthService
database DataBase

User --> WebApp: Select to log in

loop Until user enters valid credentials and exists

    WebApp --> User: Show login fields
    User --> WebApp: Fill login fields and press LogIn
    WebApp --> AuthService: Validate credentials
    AuthService --> DataBase: Validate credentials
    DataBase --> DataBase: Validate
    DataBase --> AuthService: Response
    AuthService --> WebApp: Response
    
    
    alt Credentials are incorrect or user does not exist
        WebApp --> User: Show errors and try again
    end
    
    alt Credentials are authenticated
        WebApp --> WebApp: Goes to the home page for users
    end
    
    
end
----


=== Playing a game

Selecting the game mode and playing it.

[plantuml,"Playing",png]
----

actor User
participant WebApp
participant QuestionService
database DataBase

User --> WebApp: Choose Category
User --> WebApp: Choose way of playing
WebApp --> WebApp: Show the game screen
loop For each round (10 rounds)
    WebApp --> QuestionService: Get an image and 4 options
    QuestionService --> DataBase: Get 4 rows and one of them with its image
    DataBase --> QuestionService: Response in a JSON
    QuestionService --> WebApp: Response in a JSON
    WebApp --> User: Presents the round to the user
    User --> WebApp: Choose the an answer
    WebApp --> WebApp: Checks if it is the correct one or not
    
    alt Is the correct one
        WebApp--> WebApp: Marks it on green
    end
    
    alt Is the not the correct one
        WebApp--> WebApp: Marks the correct on green and the miss on red
    end
    
end

----


=== LLMChat during a game

The application has a chatbot which can give hints during a round in the game, under no circumstances will it say the correct option. This is the procedure that follows when is invoked: 

[plantuml,"Hints",png]
----

actor User
participant WebApp
participant LLMService

User --> WebApp: Ask for a Hint on the ChatBot
WebApp --> LLMService: Send the initial prompt
LLMService --> WebApp: Returns an answer and is printed
loop Maintain a conversation
    User --> WebApp: Ask more hints
    WebApp --> LLMService: Sends the message by the user
    LLMService --> WebApp: Send an answer
    WebApp --> User: Show the hint from the LLM
end

----



=== Show statistics

Seeing the statistics of the round, and general at each category.

[plantuml,"Rankings",png]
----

actor User
participant WebApp
participant UserService
database DataBase

User --> WebApp: Login

WebApp --> UserService: Getting all statistics
UserService --> DataBase: Get all them
DataBase --> UserService: Response
UserService --> WebApp: Response

WebApp --> WebApp: See /home with rankings for all categories for all users
WebApp --> User: Allows to go through them or play a game

alt Play a game
    loop plays all rounds
    
    end
    
    WebApp--> WebApp: Shows the statistics for that concrete game
    
    alt Return Home
        WebApp--> WebApp: Goes from the game to again /home
    end
    
    alt Play Again
        WebApp--> WebApp: Play another game
    end
end

----




